version: '3.5'
services:
  node:
    build:
      context: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    depends_on:
      - db
    restart: on-failure
    ports:
      - "${PORT}:${PORT}"
  db:
    image: postgres:14
    restart: on-failure
    env_file:
      - .env
    ports:
      - '5432:5432'
